{
    "status": True,
    "message": "Category list",
    "data": [
        {
            "id": 1,
            "name": "સૂપ",
            "items": [
                {"id": 2, "name": "ટામેટા", "category": 1},
                {"id": 3, "name": "મનચાઉ", "category": 1},
                {"id": 4, "name": "બ્રોકલી", "category": 1},
                {"id": 5, "name": "મિક્સ ગ્રીન વેજીટેબલ", "category": 1},
                {"id": 6, "name": "સરગવા", "category": 1},
                {"id": 7, "name": "ટોમેટો બીટરૂટ", "category": 1},
            ],
        },
        {
            "id": 2,
            "name": "પાણી",
            "items": [
                {"id": 8, "name": "200 મિલી", "category": 2},
                {"id": 9, "name": "500 મિલી", "category": 2},
                {"id": 10, "name": "1 લિટર", "category": 2},
            ],
        },
        {
            "id": 3,
            "name": "સલાડ",
            "items": [
                {"id": 11, "name": "લીલા ચના", "category": 3},
                {"id": 12, "name": "ગાજર અને કાચી-કેરી", "category": 3},
                {"id": 13, "name": "સ્વીટ કોર્ન", "category": 3},
                {"id": 14, "name": "પંચરંગી", "category": 3},
            ],
        },
        {
            "id": 4,
            "name": "મીઠાઈ",
            "items": [
                {"id": 15, "name": "ગાજર નો હલવો", "category": 4},
                {"id": 16, "name": "અડદ દાળની સુખડી", "category": 4},
                {"id": 17, "name": "ત્રિરંગી બરફી", "category": 4},
                {"id": 18, "name": "મુંબઈ નો લીલો હલવો", "category": 4},
                {"id": 19, "name": "ડાયફૂટ દુધીનૈ હલવો", "category": 4},
                {"id": 20, "name": "પેંડા", "category": 4},
                {"id": 21, "name": "સુખડી", "category": 4},
                {"id": 22, "name": "બરફી", "category": 4},
                {"id": 23, "name": "રાજગરા નો શીરો", "category": 4},
                {"id": 24, "name": "લાપસી", "category": 4},
                {"id": 25, "name": "ગુલાબ જાંબુ", "category": 4},
            ],
        },
        {
            "id": 5,
            "name": "વેલકમ ડ્રિંક્સ",
            "items": [
                {"id": 26, "name": "મિન્ટ લેમન", "category": 5},
                {"id": 27, "name": "વોટરમેલોન મોજીટો", "category": 5},
                {"id": 28, "name": "મંગા શોટ", "category": 5},
                {"id": 29, "name": "સ્ટ્રોબેરી શોટ", "category": 5},
            ],
        },
        {
            "id": 6,
            "name": "ફરસાણ",
            "items": [
                {"id": 30, "name": "ખમણ", "category": 6},
                {"id": 31, "name": "ઢોકળા", "category": 6},
                {"id": 32, "name": "ખાંડવી/ પાટુડી", "category": 6},
                {"id": 33, "name": "સમોસા", "category": 6},
                {"id": 34, "name": "પેટીસ", "category": 6},
            ],
        },
        {
            "id": 7,
            "name": "શાક",
            "items": [
                {"id": 35, "name": "ગ્રીન ઊંધ્યું", "category": 7},
                {"id": 36, "name": "પંચકૂટિયુ", "category": 7},
                {"id": 37, "name": "મિક્ષ વેજિટેબલ", "category": 7},
                {"id": 38, "name": "મગ", "category": 7},
                {"id": 39, "name": "રીંગણ બટેકા", "category": 7},
                {"id": 40, "name": "ભરેલા રીંગણ", "category": 7},
                {"id": 41, "name": "ભરેલા કાંદા", "category": 7},
                {"id": 42, "name": "પનીર લવાબદાર", "category": 7},
                {"id": 43, "name": "કાજુ કરી", "category": 7},
                {"id": 44, "name": "કાજુ પનીર", "category": 7},
            ],
        },
        {
            "id": 8,
            "name": "તંદૂર",
            "items": [
                {"id": 45, "name": "રોટલી સાદી", "category": 8},
                {"id": 46, "name": "સાધુ રોટલી", "category": 8},
                {"id": 47, "name": "ભાખરી", "category": 8},
                {"id": 48, "name": "બાજરાના રોટલા", "category": 8},
                {"id": 49, "name": "પુરી", "category": 8},
                {"id": 50, "name": "સાદા પરાઠા", "category": 8},
                {"id": 51, "name": "તંદુરી રોટી", "category": 8},
                {"id": 52, "name": "આલુ પરાઠા", "category": 8},
            ],
        },
        {
            "id": 9,
            "name": "રાઈસ",
            "items": [
                {"id": 53, "name": "સાદા રાઈસ", "category": 9},
                {"id": 54, "name": "જીરા રાઈસ", "category": 9},
                {"id": 55, "name": "વેજ પુલાવ", "category": 9},
                {"id": 56, "name": "કાશ્મીરી પુલાવ", "category": 9},
                {"id": 57, "name": "હાંડી બિરયાની", "category": 9},
                {"id": 58, "name": "હૈદરાબાદી બિરયાની", "category": 9},
                {"id": 63, "name": "ખીચડી", "category": 9},
                {"id": 64, "name": "મસાલા ખીચડી", "category": 9},
                {"id": 65, "name": "દાળ ખીચડી", "category": 9},
            ],
        },
        {
            "id": 10,
            "name": "દાળ-કઢી",
            "items": [
                {"id": 59, "name": "સાદી દાળ", "category": 10},
                {"id": 60, "name": "દાળ ફ્રાય", "category": 10},
                {"id": 61, "name": "દાળ તડકા", "category": 10},
                {"id": 62, "name": "કાઢી", "category": 10},
            ],
        },
    ],
}
