# Generated by Django 5.1.4 on 2025-01-27 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StokeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('alert', models.CharField(max_length=50)),
            ],
        ),
    ]
