# Generated by Django 5.1.4 on 2025-02-11 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventbooking',
            name='extra_service_amount',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
