# Generated by Django 5.1.4 on 2025-01-27 13:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_stokeitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='stokeitem',
            name='type',
            field=models.CharField(choices=[('KG', 'કિલોગ્રામ'), ('L', 'લીટર'), ('QTY', 'જથ્થો')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
