# Generated by Django 5.1.4 on 2025-02-11 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_eventbooking_extra_service_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='total_extra_amount',
            field=models.DecimalField(decimal_places=0, default='600000', max_digits=250),
            preserve_default=False,
        ),
    ]
