# Generated by Django 5.1.4 on 2025-02-11 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_payment_total_extra_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventbooking',
            name='extra_service',
            field=models.JSONField(default=dict),
        ),
    ]
