# Generated by Django 5.1.4 on 2025-01-28 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_stokeitem_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stokeitem',
            name='alert',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='stokeitem',
            name='quantity',
            field=models.DecimalField(decimal_places=0, max_digits=100),
        ),
    ]
