# Generated by Django 5.1.4 on 2025-01-29 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_stokeitem_alert_alter_stokeitem_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='StokeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='stokeitem',
            name='type',
            field=models.CharField(choices=[('KG', 'કિલોગ્રામ'), ('G', 'ગ્રામ'), ('L', 'લીટર'), ('ML', 'મિલીલીટર'), ('QTY', 'જથ્થો')], max_length=10),
        ),
        migrations.AddField(
            model_name='stokeitem',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stokeitem', to='app.stokecategory'),
            preserve_default=False,
        ),
    ]
