# Generated by Django 5.1.4 on 2025-01-31 05:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_eventbooking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='stokeitem',
            name='pr_kg_price',
            field=models.CharField(default=500, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stokeitem',
            name='total_price',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
