# Generated by Django 5.1.4 on 2025-01-31 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_stokeitem_pr_kg_price_stokeitem_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stokeitem',
            old_name='pr_kg_price',
            new_name='nte_price',
        ),
    ]
