# Generated by Django 5.1.4 on 2025-01-31 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='id',
        ),
        migrations.AlterField(
            model_name='payment',
            name='bill_no',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
