# Generated by Django 5.1.4 on 2025-01-31 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_payment_id_alter_payment_bill_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='billed_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='app.eventbooking', unique=True),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(fields=('billed_to',), name='unique_billed_to'),
        ),
    ]
