# Generated by Django 5.1.4 on 2025-02-03 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_payment_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='pending_amount',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='settlement_amount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='total_amount',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_amount',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
