# Generated by Django 5.1.4 on 2025-02-03 06:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_payment_pending_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='advance_amount',
            field=models.DecimalField(decimal_places=0, default=None, max_digits=10),
            preserve_default=False,
        ),
    ]
