# Generated by Django 5.1.4 on 2025-02-03 08:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_payment_advance_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventbooking',
            name='advance_payment_mode',
            field=models.CharField(choices=[('CASH', 'CASH'), ('CHEQUE', 'CHEQUE'), ('BANK_TRANSFER', 'BANK TRANSFER'), ('ONLINE', 'ONLINE'), ('OTHER', 'OTHER')], max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_mode',
            field=models.CharField(choices=[('CASH', 'CASH'), ('CHEQUE', 'CHEQUE'), ('BANK_TRANSFER', 'BANK TRANSFER'), ('ONLINE', 'ONLINE'), ('OTHER', 'OTHER')], max_length=20),
        ),
    ]
